// Shared Sector Mapping Logic

export const SECTOR_MAP: Record<string, string> = {
    'RELIANCE': 'Energy',
    'TCS': 'Technology',
    'INFY': 'Technology',
    'WIPRO': 'Technology',
    'HDFCBANK': 'Finance',
    'ICICIBANK': 'Finance',
    'SBIN': 'Finance',
    'KOTAKBANK': 'Finance',
    'AXISBANK': 'Finance',
    'ITC': 'FMCG',
    'HINDUNILVR': 'FMCG',
    'BRITANNIA': 'FMCG',
    'BAJFINANCE': 'Finance',
    'MARUTI': 'Automobile',
    'TATAMOTORS': 'Automobile',
    'M&M': 'Automobile',
    'SUNPHARMA': 'Pharma',
    'DRREDDY': 'Pharma',
    'CIPLA': 'Pharma',
    'ONGC': 'Energy',
    'COALINDIA': 'Energy',
    'BHARTIARTL': 'Telecom',
    'LT': 'Infrastructure',
    'TITAN': 'Consumer',
    'ASIANPAINT': 'Consumer',
    'ULTRACEMCO': 'Materials',
    'TATASTEEL': 'Materials',
    'HINDALCO': 'Materials',
    'JSWSTEEL': 'Materials',
    'NTPC': 'Power',
    'POWERGRID': 'Power',
    'ADANIENT': 'Diversified',
    'ADANIPORTS': 'Infrastructure',
    'HCLTECH': 'Technology',
    'TECHM': 'Technology',
    'EICHERMOT': 'Automobile',
    'HEROMOTOCO': 'Automobile',
    'BAJAJFINSV': 'Finance',
    'NESTLEIND': 'FMCG',
    'GRASIM': 'Materials',
    'DIVISLAB': 'Pharma',
};

export const SECTOR_COLORS: Record<string, string> = {
    'Technology': '#2196f3',
    'Finance': '#4caf50',
    'Energy': '#ff9800',
    'FMCG': '#9c27b0',
    'Automobile': '#f44336',
    'Pharma': '#00bcd4',
    'Telecom': '#e91e63',
    'Infrastructure': '#607d8b',
    'Consumer': '#7b1fa2',
    'Materials': '#795548',
    'Power': '#ffc107',
    'Diversified': '#3f51b5',
    'Others': '#9e9e9e',
};

export const getSector = (symbol: string): string => SECTOR_MAP[symbol] || 'Others';
